apiVersion: v1
kind: Secret
metadata:
  name: ssh-private-repo-secret
  namespace: argocd
  labels:
     argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@source.datanerd.us:vkodavali/newrelic-k8s-integration.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACACwN4DPy625WLk8CRT6h0RCfBA+tc7Q4vnt8ku45GeSgAAAIjeCFLK3ghSygAAAAtzc2gtZWQyNTUxOQAAACACwN4DPy625WLk8CRT6h0RCfBA+tc7Q4vnt8ku45GeSgAAAEDW7C8iJb5TDJiN9aKEnk2iQPo3l90fF9gC59ITscJfHgLA3gM/LrblYuTwJFPqHREJ8ED61ztDi+e3yS7jkZ5KAAAAAAECAwQF
    -----END OPENSSH PRIVATE KEY-----