newrelic-infrastructure:
  # newrelic-infrastructure.enabled -- Install the newrelic-infrastructure chart
  enabled: true

nri-prometheus:
  # nri-prometheus.enabled -- Install the nri-prometheus chart
  enabled: false

nri-metadata-injection:
  # nri-metadata-injection.enabled -- Install the nri-metadata-injection chart
  enabled: true

kube-state-metrics:
  # kube-state-metrics.enabled -- Install the kube-state-metrics chart
  enabled: true

nri-kube-events:
  # nri-kube-events.enabled -- Install the nri-kube-events chart
  enabled: true

newrelic-logging:
  # newrelic-logging.enabled -- Install the newrelic-logging chart
  enabled: true

newrelic-pixie:
  # newrelic-pixie.enabled -- Install the newrelic-pixie
  enabled: false

pixie-chart:
  # pixie-chart.enabled -- Install the pixie-chart chart
  enabled: false

newrelic-infra-operator:
  # newrelic-infra-operator.enabled -- Install the newrelic-infra-operator chart
  enabled: false

newrelic-prometheus-agent:
  # newrelic-prometheus-agent.enabled -- Install the newrelic-prometheus-agent chart
  enabled: true

newrelic-eapm-agent:
  # newrelic-eapm-agent.enabled -- Install the nr-eapm-agent
  enabled: false

k8s-agents-operator:
  # k8s-agents-operator.enabled -- Install the k8s-agents-operator chart
  enabled: true

newrelic-k8s-metrics-adapter:
  # newrelic-k8s-metrics-adapter.enabled -- Install the newrelic-k8s-metrics-adapter chart
  enabled: false

global:
  # -- The cluster name for the Kubernetes cluster.
  cluster: docker-desktop

  # -- The license key for your New Relic Account.
  licenseKey: eu01xxcb60346203f2952330fbe72ccdFFFFNRAL
  insightsKey: ""
  customSecretName: ""
  customSecretLicenseKey: ""

  labels: {}
  podLabels: {}

  images:
    registry: ""
    pullSecrets: []

  serviceAccount:
    annotations: {}
    create:
    name:

  hostNetwork:
  dnsConfig: {}

  priorityClassName: ""
  podSecurityContext: {}
  containerSecurityContext: {}

  affinity: {}
  nodeSelector: {}
  tolerations: []

  customAttributes: {}

  lowDataMode: true
  privileged: true
  fargate:

  proxy:  

  nrStaging:
  fedramp:
    enabled: 

  verboseLog:

  # Example of monitoring Redis integration with autodiscovery
  newrelic-infrastructure:
    integrations:
      nri-redis-sampleapp:
        discovery:
          command:
            exec: /var/db/newrelic-infra/nri-discovery-kubernetes --tls --port 10250
            match:
              label.app: sampleapp
        integrations:
          - name: nri-redis
            env:
              HOSTNAME: ${discovery.ip}
              PORT: 6379
            labels:
              env: test